import libtcodpy as libtcod

SCREEN_WIDTH = 120
SCREEN_HEIGHT = 60


#map size
MAP_WIDTH = 80
MAP_HEIGHT = 50

CAMERA_WIDTH = 80
CAMERA_HEIGHT = 50
FREEMOVE_WIDTH = 15
FREEMOVE_HEIGHT = 10

#GUI parameters
BAR_WIDTH = 20
PANEL_HEIGHT = 10
PANEL_Y = SCREEN_HEIGHT - PANEL_HEIGHT
MSG_X = BAR_WIDTH + 2
MSG_WIDTH = SCREEN_WIDTH - BAR_WIDTH - 2
MSG_HEIGHT = PANEL_HEIGHT - 1

#map gen parameters
MAX_ROOM_MONSTERS = 3
ROOM_MAX_SIZE = 25  # ALL TO BE CHANGED LATER OF COURSE
ROOM_MIN_SIZE = 6
MAX_ROOMS = 30
 
LIMIT_FPS = 20  #20 frames-per-second maximum
FOV_ALGO = 0  #default FOV algorithm
FOV_LIGHT_WALLS = True
TORCH_RADIUS = 10
INVENTORY_WIDTH = SCREEN_WIDTH - 10
CHARACTER_SCREEN_WIDTH = 40

LIGHTNING_DAMAGE = 20 
LIGHTNING_RANGE = 5
FIREBALL_DAMAGE = 12
FIREBALL_RADIUS = 4
POTHEAL_AMOUNT = 10

LEVEL_UP_BASE = 50
LEVEL_UP_FACTOR = 75
LEVEL_SCREEN_WIDTH = 40


color_dark_wall = libtcod.Color(0, 0, 100)
color_dark_ground = libtcod.Color(50, 50, 150)
color_light_wall = libtcod.Color(130, 110, 50)
color_light_ground = libtcod.Color(200, 180, 50)